version: "3.8"

services:
  postgredb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5430:5432
    expose:
      - 5430
  app:
    depends_on:
      - postgredb
    build: ./FileManagement
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgredb:5432/postgres",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "admin123",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
